print('hello world')
print('what is your name?')
myname=input()
print('It is good to meet u '+ myname)
print('The length of your name is:')
print(len(myname))
print('What is your age?')
myage=input()
print('You will be '+ str(int(myage)+1) +' in a year')
